49_2: ../../lib/error_functions.c mmap_xfr_reader.c mmap_xfr_writer.c
	gcc -o mmap_xfr_reader.out mmap_xfr_reader.c ../../lib/error_functions.c ../../svsem/binary_sems.c
	gcc -o mmap_xfr_writer.out mmap_xfr_writer.c ../../lib/error_functions.c ../../svsem/binary_sems.c
